on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: ubuntu-latest  # Змініть на відповідну ОС, яку ви використовуєте

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Playwright browsers
        run: npx playwright install

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
        
      - name: Install dependencies and run tests
        run: npm install && npm test
