name: Run Playwright tests

on:
  push:
    branches:
      - main

jobs:
  e2e-tests:
    runs-on: macos-latest

    steps:
    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      uses: microsoft/playwright-github-action@v1.5.5
