on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm install

      - name: Run Playwright tests
        uses: microsoft/playwright-github-action@v1
