on:
  push:
    branches:
    - main

jobs:
  e2e-tests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20
          
      - name: Install Playwright browsers
        run: npx @playwright/test install

      - uses: microsoft/playwright-github-action@v1
        
      - name: Install dependencies and run tests
        run: npm install && npm test
